//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18051
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LBCMapping.Mailer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="EmAppManager", ConfigurationName="Mailer.MailerSoap")]
    public interface MailerSoap {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément subject de l'espace de noms EmAppManager n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="EmAppManager/SendSmtpMail", ReplyAction="*")]
        LBCMapping.Mailer.SendSmtpMailResponse SendSmtpMail(LBCMapping.Mailer.SendSmtpMailRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmtpMailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmtpMail", Namespace="EmAppManager", Order=0)]
        public LBCMapping.Mailer.SendSmtpMailRequestBody Body;
        
        public SendSmtpMailRequest() {
        }
        
        public SendSmtpMailRequest(LBCMapping.Mailer.SendSmtpMailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="EmAppManager")]
    public partial class SendSmtpMailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string body;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string to;
        
        public SendSmtpMailRequestBody() {
        }
        
        public SendSmtpMailRequestBody(string subject, string body, string to) {
            this.subject = subject;
            this.body = body;
            this.to = to;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmtpMailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmtpMailResponse", Namespace="EmAppManager", Order=0)]
        public LBCMapping.Mailer.SendSmtpMailResponseBody Body;
        
        public SendSmtpMailResponse() {
        }
        
        public SendSmtpMailResponse(LBCMapping.Mailer.SendSmtpMailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SendSmtpMailResponseBody {
        
        public SendSmtpMailResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MailerSoapChannel : LBCMapping.Mailer.MailerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MailerSoapClient : System.ServiceModel.ClientBase<LBCMapping.Mailer.MailerSoap>, LBCMapping.Mailer.MailerSoap {
        
        public MailerSoapClient() {
        }
        
        public MailerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MailerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MailerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MailerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LBCMapping.Mailer.SendSmtpMailResponse LBCMapping.Mailer.MailerSoap.SendSmtpMail(LBCMapping.Mailer.SendSmtpMailRequest request) {
            return base.Channel.SendSmtpMail(request);
        }
        
        public void SendSmtpMail(string subject, string body, string to) {
            LBCMapping.Mailer.SendSmtpMailRequest inValue = new LBCMapping.Mailer.SendSmtpMailRequest();
            inValue.Body = new LBCMapping.Mailer.SendSmtpMailRequestBody();
            inValue.Body.subject = subject;
            inValue.Body.body = body;
            inValue.Body.to = to;
            LBCMapping.Mailer.SendSmtpMailResponse retVal = ((LBCMapping.Mailer.MailerSoap)(this)).SendSmtpMail(inValue);
        }
    }
}
